# Generated by Django 6.0.6 on 2026-06-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='fnished_date',
            new_name='finished_date',
        ),
    ]
